### api test
GET http://localhost:8000

#apis
### Post new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "firstName": "Bishal",
    "lastName": "karki",
    "email": "kb@g.com",
    "password": "asfgh",
    "confirmPassword": "asfgh"
}